# Generated by Django 4.1.5 on 2023-01-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_post_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
