# Generated by Django 4.1.5 on 2023-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_utcoffset_customuser_utc_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="users_avatars/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Онлайн"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Последняя активность"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="post_count",
            field=models.IntegerField(default=0, verbose_name="Счетчик сообщений"),
        ),
        migrations.AlterField(
            model_name="utcoffset",
            name="description",
            field=models.CharField(default="", max_length=20, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="utcoffset",
            name="offset",
            field=models.IntegerField(default=0, verbose_name="Смещение"),
        ),
    ]
