# Generated by Django 4.1.5 on 2023-08-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_customuser_image_alter_customuser_is_online_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utcoffset",
            name="description",
            field=models.CharField(
                default="MSK+0", max_length=20, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="utcoffset",
            name="offset",
            field=models.IntegerField(default=3, verbose_name="Смещение"),
        ),
    ]
