# Generated by Django 4.1.5 on 2023-08-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_utcoffset_description_alter_utcoffset_offset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="utc_offset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.utcoffset",
                verbose_name="Часовой пояс",
            ),
        ),
    ]
