# Generated by Django 4.1.5 on 2023-01-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_biggroup_descr_alter_group_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='', verbose_name='Текст сообщения'),
        ),
    ]
