# Generated by Django 4.1.5 on 2023-08-14 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0007_topic_first_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biggroup",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="BigGroup",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="biggroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="biggroup",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="biggroup",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата опубликования"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Group",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="big_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Group",
                to="main.biggroup",
                verbose_name="Большая группа",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="descr",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="group",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата опубликования"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Post",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(default="", verbose_name="Текст"),
        ),
        migrations.AlterField(
            model_name="post",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Дата опубликования"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата опубликования"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Post",
                to="main.topic",
                verbose_name="Тема",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Topic",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="first_post",
            field=models.TextField(default="", verbose_name="Первое сообщение - текст"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="first_post_image",
            field=models.ImageField(
                blank=True,
                upload_to="post_images/",
                verbose_name="Первое сообщение - изображение",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Topic",
                to="main.group",
                verbose_name="Группа",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активно"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата опубликования"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Счетчик сообщений"),
        ),
    ]
