# Generated by Django 4.1.5 on 2023-08-16 16:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_biggroup_author_alter_biggroup_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="biggroup",
            name="author",
        ),
        migrations.RemoveField(
            model_name="group",
            name="author",
        ),
        migrations.RemoveField(
            model_name="group",
            name="descr",
        ),
    ]
