version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5  
      
  backend:
    image: ildarbon/abc-forum_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/app/media

  nginx:
    image: ildarbon/abc-forum_nginx
    env_file: .env
    ports:
      - 8001:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
